### PR TITLE
Fix problems with template dialog

### LINKED ISSUE #1603: Process template dialog no longer waits for checks before going to next steps panel
We have a number of checks we perform before advancing to next steps processing a template. The wizard no longer waits for the checks. It advances to the next wizard step right away before the checks are complete.

openshift web console 2017-05-26 16-28-28

cc @jeff-phillips-18 @jwforres

### LINKED ISSUE #1620: Parameters are not properly cleared when selecting a second template from the catalog
Only happens in the template dialog in the new experience.

```
angular.js:14199 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: paramName in $ctrl.parameters.generated, Duplicate key: string:SOURCE_REPOSITORY_REF, Duplicate value: SOURCE_REPOSITORY_REF
http://errors.angularjs.org/1.5.11/ngRepeat/dupes?p0=paramName%20in%20%24ct…eters.generated&p1=string%3ASOURCE_REPOSITORY_REF&p2=SOURCE_REPOSITORY_REF
    at angular.js:68
    at ngRepeatAction (angular.js:30586)
    at $watchCollectionAction (angular.js:17697)
    at Scope.$digest (angular.js:17836)
    at Scope.$apply (angular.js:18102)
    at Array.flushOnChangesQueue (angular.js:8280)
    at Scope.$digest (angular.js:17887)
    at Scope.$apply (angular.js:18102)
    at HTMLAnchorElement.<anonymous> (angular.js:26597)
    at HTMLAnchorElement.dispatch (jquery.js:4435)
```

@jwforres fyi

### LINKED ISSUE #1622: When template has no parameters, select project is missing
openshift web console 2017-05-31 10-56-46

### LINKED ISSUE #1630: Template messages showing up for previous template
New experience / template dialog only. The template message and processed parameters are also broken. No message shows up for the first template, and the second template shows the message from the first.

Notice I'm seeing the message from the Cake PHP template when I instantiated the MongoDB template.

screen shot 2017-06-01 at 11 40 33 am

cc @jwforres

### PR DESCRIPTION
**Pull request by spadgett**
- Validate before advancing to next steps (closes #1603)
- Fix issue where parameters from previous templates were not fully cleared when selecting another template (closes #1620)
- Fix issue where previous template message is displayed for second template (closes #1630)
- Fix issue where project select doesn't show up when template has no parameters (closes #1622)
- Fix issue where Create button flickers on template dialog load

### CODE REVIEW

File: app/scripts/directives/processTemplateDialog.js [hunk 1]
```diff
@@ -67,6 +82,11 @@ function ProcessTemplateDialog($scope, DataService) {
     }
   };
 
+  $scope.$on('templateInstantiated', function(event, message) {
```
Comment (jwforres) [inline app/scripts/directives/processTemplateDialog.js]: i'm seeing two listeners for templateInstantiated

File: app/scripts/directives/processTemplateDialog.js [hunk 2]
```diff
@@ -52,13 +52,28 @@ function ProcessTemplateDialog($scope, DataService) {
...
+
   ctrl.$onDestroy = function() {
     clearValidityWatcher();
   };
 
-  $scope.$on('templateInstantiated', function(event, message) {
-    ctrl.selectedProject = message.project;
-  });
+  ctrl.next = function(step) {
+    if (step.stepId === 'configuration') {
```
Comment (jeff-phillips-18) [inline app/scripts/directives/processTemplateDialog.js]: Better to use ctrl.configStep.id than 'configuration'

File: app/scripts/directives/processTemplateDialog.js [hunk 3]
```diff
@@ -52,13 +52,28 @@ function ProcessTemplateDialog($scope, DataService) {
...
+      instantiateTemplate();
+      // Don't advance wizard automatically. Wait for template validation to complete.
+      return false;
+    }
+
+    if (step.stepId === 'results') {
```
Comment (jeff-phillips-18) [inline app/scripts/directives/processTemplateDialog.js]: ctrl.resultsStep.id

File: app/scripts/directives/processTemplateDialog.js (hunk 2 above)
Comment (jeff-phillips-18) [inline app/scripts/directives/processTemplateDialog.js]: Better to use ctrl.configStep.id instead of 'configuration'

**Comment by spadgett** [comment]
Updated. Added fixes for additional problems I noticed (see description).

File: app/views/directives/process-template.html [hunk 4]
```diff
@@ -4,7 +4,7 @@
       <select-project ng-if="!$ctrl.project" selected-project="$ctrl.selectedProject" name-taken="$ctrl.projectNameTaken"></select-project>
     </template-options>
     <!-- TODO: Also support advanced options for new projects. -->
-    <div ng-if="$ctrl.isDialog && $ctrl.selectedProject.metadata.uid && $ctrl.template" class="form-group">
```
Comment (spadgett) [inline app/views/directives/process-template.html]: Added `ng-if="template"` around the entire dialog to fix #1620

**Comment by spadgett** [comment]
Added a fix for #1622 as well.

File: app/views/_templateopt.html [hunk 5]
```diff
@@ -1,8 +1,7 @@
 <div
     class="template-options"
-    ng-show="parameters.length"
```
Comment (spadgett) [inline app/views/_templateopt.html]: This fixes #1622

**Comment by spadgett** [comment]
@jwforres Investigating another regression #1630

File: app/views/directives/process-template-dialog.html [hunk 6]
```diff
@@ -41,7 +43,7 @@
           </div>
         </div>
         <div class="order-service-config">
-          <div ng-include="step.view" class="wizard-pf-main-form-contents"></div>
+          <div ng-if="step.selected" ng-include="step.view" class="wizard-pf-main-form-contents"></div>
```
Comment (spadgett) [inline app/views/directives/process-template-dialog.html]: @jwforres This fixes #1630

**Comment by jwforres** [comment]
[merge][severity:blocker]
