### PR TITLE
Fix reloading of landing page after guided tour ends

### LINKED ISSUE #1509: Ending the Guided Tour for the Landing Page reloads the page
When finishing the landing page guided tour, the landing page gets reloaded.

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes #1509

### CODE REVIEW

File: app/scripts/controllers/landingPage.js [hunk 1]
```diff
@@ -84,11 +86,16 @@ angular.module('openshiftConsole')
...
+      if (newUrl.indexOf('startTour') > 0) {
+        event.preventDefault();
+        if (tourEnabled) {
+          $scope.startGuidedTour();
+        }
+      }
+    });
+
+    $scope.$on('destroy', function() {
+      deregisterLocationStart();
```
Comment (spadgett) [inline app/scripts/controllers/landingPage.js]: I don't think this is needed for `$scope.$on` listeners. They'll be cleaned up automatically. (Although it's required for `$rootScope.$on`)

File: app/scripts/controllers/landingPage.js [hunk 2]
```diff
@@ -84,11 +86,16 @@ angular.module('openshiftConsole')
...
 
-    function resetRouteParams() {
-      // Reset the route params in the next digest cycle
-      $timeout(function() {
-        $location.replace();
-        $location.search('startTour', null);
-      });
-    }
+    var deregisterLocationStart = $scope.$on('$locationChangeStart', function(event, newUrl) {
+      if (newUrl.indexOf('startTour') > 0) {
```
Comment (spadgett) [inline app/scripts/controllers/landingPage.js]: Are you able to use `$location.search().startTour` instead of `indexOf`?

File: app/scripts/controllers/landingPage.js [hunk 3]
```diff
@@ -84,11 +86,16 @@ angular.module('openshiftConsole')
...
+        event.preventDefault();
+        if (tourEnabled) {
```
Comment (spadgett) [inline app/scripts/controllers/landingPage.js]: Might be better to only add the location change listener when the tour is enabled.

File: app/scripts/controllers/landingPage.js [hunk 4]
```diff
@@ -84,11 +86,16 @@ angular.module('openshiftConsole')
...
-    function resetRouteParams() {
-      // Reset the route params in the next digest cycle
-      $timeout(function() {
-        $location.replace();
-        $location.search('startTour', null);
-      });
-    }
+    var deregisterLocationStart = $scope.$on('$locationChangeStart', function(event, newUrl) {
+      if (newUrl.indexOf('startTour') > 0) {
+        event.preventDefault();
```
Comment (spadgett) [inline app/scripts/controllers/landingPage.js]: Is this still needed with `reloadOnSearch: false`?

Comment (jeff-phillips-18) [inline app/scripts/controllers/landingPage.js]: yes, otherwise the URL changes which would adversely effect bookmarks.

Comment (spadgett) [inline app/scripts/controllers/landingPage.js]: Ah OK, understood. I'd add a comment saying this is to prevent the URL from changing in the location bar.

Comment (spadgett) [inline app/scripts/controllers/landingPage.js]: (As opposed to preventing the page from reloading.)

File: app/scripts/controllers/landingPage.js (hunk 2 above)
Comment (jeff-phillips-18) [inline app/scripts/controllers/landingPage.js]: Yes, fixed.

File: app/scripts/controllers/landingPage.js (hunk 4 above)
Comment (jeff-phillips-18) [inline app/scripts/controllers/landingPage.js]: Done.

File: app/scripts/controllers/landingPage.js (hunk 3 above)
Comment (jeff-phillips-18) [inline app/scripts/controllers/landingPage.js]: Done.

File: app/scripts/controllers/landingPage.js (hunk 1 above)
Comment (jeff-phillips-18) [inline app/scripts/controllers/landingPage.js]: Removed.

**Comment by spadgett** [comment]
[test]
