### PR TITLE
Fix problems with env valueFrom for DC hooks

### LINKED ISSUE #2460: Runtime error in env variable editor
This error occurs in the deployment config editor on load.

screen shot 2017-11-06 at 8 14 06 am

```
Error: option is undefined
findSecret/<.object<@https://localhost:9000/dev-console/scripts/services/keyValueEditorUtils.js:200:15
baseFindIndex@https://localhost:9000/dev-console/bower_components/lodash/lodash.js:823:11
findIndex@https://localhost:9000/dev-console/bower_components/lodash/lodash.js:7275:14
createFind/<@https://localhost:9000/dev-console/bower_components/lodash/lodash.js:5098:21
findSecret@https://localhost:9000/dev-console/scripts/services/keyValueEditorUtils.js:199:21
findReferenceValue@https://localhost:9000/dev-console/scripts/services/keyValueEditorUtils.js:212:19
findReferenceValueForEntries/<@https://localhost:9000/dev-console/scripts/services/keyValueEditorUtils.js:221:32
arrayEach@https://localhost:9000/dev-console/bower_components/lodash/lodash.js:537:11
forEach@https://localhost:9000/dev-console/bower_components/lodash/lodash.js:9359:14
findReferenceValueForEntries@https://localhost:9000/dev-console/scripts/services/keyValueEditorUtils.js:218:11
.controller</<@https://localhost:9000/dev-console/scripts/directives/keyValueEditor.js:304:17
$digest@https://localhost:9000/dev-console/bower_components/angular/angular.js:17836:23
$apply@https://localhost:9000/dev-console/bower_components/angular/angular.js:18102:13
done@https://localhost:9000/dev-console/bower_components/angular/angular.js:12082:36
completeRequest@https://localhost:9000/dev-console/bower_components/angular/angular.js:12291:7
requestLoaded@https://localhost:9000/dev-console/bower_components/angular/angular.js:12219:9
```

cc @jwforres

### PR DESCRIPTION
**Pull request by spadgett**
screen shot 2017-11-06 at 8 26 19 am

* Avoid adding an `undefined` element to value from array depending on the
  order that config maps and secrets load
* Fix typo passing config maps to edit-lifecycle-hooks
* Show valueFrom values for hooks when viewing the deployment config

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1509842
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1509819
Fixes #2460

/kind bug
/assign @jwforres

### CODE REVIEW

File: app/scripts/directives/lifecycleHook.js [hunk 1]
```diff
@@ -123,7 +123,9 @@ angular.module("openshiftConsole")
 
         $scope.valueFromObjects = [];
         $scope.$watchGroup(['availableSecrets', 'availableConfigMaps'], function() {
-          $scope.valueFromObjects = ($scope.availableSecrets || []).concat($scope.availableConfigMaps);
```
Comment (spadgett) [inline app/scripts/directives/lifecycleHook.js]: @jwforres This could push an `undefined` element into the array if `availableConfigMaps` was not initialized yet, causing #2460
