### PR TITLE
Don't resize log viewer before visible

### LINKED ISSUE #1278: Logs resizing incorrectly
screen shot 2017-02-21 at 12 19 51 pm

### PR DESCRIPTION
**Pull request by spadgett**
Fixes a bug where the log viewer could be sized too large for the window. The top offset was wrong since we were calculating before the log was displayed.

Closes #1278

### CODE REVIEW

File: app/scripts/directives/logViewer.js [hunk 1]
```diff
@@ -208,6 +212,37 @@ angular.module('openshiftConsole')
...
+                // To avoid flicker, the log doesn't display until sized === true
+                $scope.$evalAsync(function() {
+                  $scope.sized = true;
+                });
+              };
+
+              var retries = 0;
+              visibleInterval = setInterval(function() {
+                if (retries > 10) {
+                  done();
```
Comment (jwforres) [inline app/scripts/directives/logViewer.js]: in this case will the log still show up and just not fill the height?

Comment (spadgett) [inline app/scripts/directives/logViewer.js]: Yes

**Comment by jwforres** [comment]
[merge]
