### PR TITLE
Better conflict handling for env var edits

### LINKED ISSUE #621: ENV variable manager and crashing pods
This left a bad experience for a user who's pod kept crashing due to an incorrectly set ENV variable. 

When he went to edit the ENV variable in the console, because the pod kept restarting it was triggering a restart. By the time he had edited the ENV variable, the pod would've crashed and tried again, the web console would then force him to refresh the ENV variables and start again.

### LINKED ISSUE #676: Got both success and warning alerts when saving env variables
Sometimes when you save env variables, you see both a success alert saying the resource was updated and a warning saying the resource was updated in the background. Neither of these alerts were visible before I clicked "Save." This was editing a deployment.

openshift_web_console

/cc @jwforres @benjaminapetersen

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #621
Fixes #676

@jwforres @rhamilto FYI

Resources updated:
- [x] Deployment Config
- [x] Deployment
- [x] Replica Set
- [x] Replication Controller
- [x] Stateful Set

### CODE REVIEW

File: app/scripts/controllers/deploymentConfig.js [hunk 1]
```diff
@@ -56,18 +56,43 @@ angular.module('openshiftConsole')
...
+      // deployment config object.
+      if (EnvironmentService.isEnvironmentEqual(current, previous)) {
+        $scope.updatedDeploymentConfig = EnvironmentService.mergeEdits($scope.updatedDeploymentConfig, current);
+        return;
+      }
+
+      previousEnvConflict = true;
+      $scope.alerts["background_update"] = {
+        type: "warning",
+        message: "This deployment configuration has been updated in the background. Saving your changes may create a conflict or cause loss of data.",
```
Comment (jwforres) [inline app/scripts/controllers/deploymentConfig.js]: now that we know the env vars are what caused the conflict, i'm thinking we should update the message to be more specific

File: app/scripts/services/environment.js [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+      // Note: This modifies object. It should only be called on a copy.
+      compactEnvironment: function(object) {
+        var containers = getContainers(object);
+        _.each(containers, function(container) {
+          container.env = keyValueEditorUtils.compactEntries(container.env);
+        });
+      },
+
+      // Copy and normalize the environment for editing using the key value editor.
+      copy: function(object) {
```
Comment (jwforres) [inline app/scripts/services/environment.js]: hmm, i wouldn't expect a function called copy to also be doing normalization

File: app/scripts/services/environment.js [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+      isEnvironmentEqual: function(left, right) {
+        var leftContainers = getContainers(left);
+        var rightContainers = getContainers(right);
+        if (leftContainers.length !== rightContainers.length) {
+          return false;
+        }
+
+        var i, leftEnv, rightEnv;
+        for (i = 0; i < leftContainers.length; i++) {
+          leftEnv = leftContainers[i].env || [];
```
Comment (jwforres) [inline app/scripts/services/environment.js]: i feel like we should be validating that the container names are actually the same, what if i took out a container, added a brand new container, the length of containers array is the same but they are no longer equal. Especially since merge edits below assumes containers in the same positions are in fact the same.

**Comment by spadgett** [comment]
@jwforres Updated. I'd like to do some more testing, but the code should be ready for another review.

**Comment by spadgett** [comment]
Still need to sort out #676, which I suspect is a race between the PUT callback and watch callback.

File: app/scripts/services/environment.js [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+        }
+
+        var i, leftEnv, rightEnv;
+        for (i = 0; i < leftContainers.length; i++) {
+          // If a container name has changed, consider it a conflict.
+          if (leftContainers[i].name !== rightContainers[i].name) {
+            return false;
+          }
+
+          // Check if any of the variable names are values are different.
```
Comment (jwforres) [inline app/scripts/services/environment.js]: typo in the comment 'variable names or values'

**Comment by jwforres** [comment]
just one nit, otherwise LGTM

**Comment by spadgett** [comment]
Thanks @jwforres 

Updated with a fix for the PUT/watch race (#676).

File: app/scripts/controllers/deployment.js [hunk 5]
```diff
@@ -131,28 +156,23 @@ angular.module('openshiftConsole')
...
+              updateHPAWarnings();
 
-              if ($scope.forms.deploymentEnvVars.$pristine) {
-                copyDeploymentAndEnsureEnv(deployment);
+              updateEnvironment(deployment, previous);
+
+              // Wait for a pending save to complete to avoid a race between the PUT and the watch callbacks.
+              if (saveEnvPromise) {
+                saveEnvPromise.finally(function() {
+                  updateEnvironment(deployment, previous);
```
Comment (spadgett) [inline app/scripts/controllers/deployment.js]: @jwforres It looks like calling `updateEnvironment` from `saveEnvPromise.finally` is enough.

* If the PUT succeeds, the success callback in `saveEnvVars` will set the form to pristine before `updateEnvironment` is called. When the form is pristine, `updateEnvironment` will simply copy the new values.
* If the PUT fails, the normal conflict checking is performed by `updateEnvironment`.

**Comment by jwforres** [comment]
Update LGTM

**Comment by spadgett** [comment]
> Update LGTM

Thanks @jwforres. Tested various scenarios with all of the types (deployment configs, deployments, replication controllers, and replica sets). Also checked the read-only view of the stateful set environment.

[merge]

**Comment by spadgett** [comment]
```
Running "add-redirect-uri" task
oc --server https://localhost:8443 patch oauthclient/openshift-web-console -p {"redirectURIs":["https://localhost:9000/"]}
>> Error: The connection to the server localhost:8443 was refused - did you specify the right host or port?
```

[merge]
